In [1]:
import numpy as np
import math
from copy import deepcopy
%matplotlib notebook
from matplotlib import pyplot as plt
from networkx import grid_graph
%pylab inline
%load_ext autoreload
%autoreload 2

from cvf20.unionfind import UnionFind as UF

Populating the interactive namespace from numpy and matplotlib


# 1. Generalized All-Pairs Shortest Path Problem

### a) All-pairs shortest path

In [2]:
onestep     = np.array([[0,6.,math.inf,math.inf,math.inf], \
                        [math.inf,0,math.inf, math.inf, 2.], \
                        [1, 5., 0, 8., math.inf], \
                        [math.inf, 2., math.inf, 0, math.inf],\
                        [math.inf, math.inf, 4., math.inf, 0]])
for row in onestep:
    print(row)

[ 0.  6. inf inf inf]
[inf  0. inf inf  2.]
[ 1.  5.  0.  8. inf]
[inf  2. inf  0. inf]
[inf inf  4. inf  0.]


In [11]:
def matrixminsum(matrix):
    dim = matrix.shape[0]
    assert(matrix.shape[0] == matrix.shape[1])
    
    multisteps = deepcopy(matrix)
    result = deepcopy(matrix)

    iterations = 0
    while 1:
        iterations += 1
        for i in range(dim):
            row = multisteps[i]
            for j in range(dim):
                col = matrix[:, j]
                result[i][j] = np.min(row + col)
                
        if (multisteps == result).all():
            print("minsum converged after", iterations - 1, "iterations")
            return result, iterations-1
        elif iterations > dim:
            raise "Negative Cycle detected"
            return None
        else:
            multisteps = deepcopy(result)

In [12]:
shortestpaths, iterations = matrixminsum(onestep)
print(shortestpaths)

minsum converged after 3 iterations
[[ 0.  6. 12. 20.  8.]
 [ 7.  0.  6. 14.  2.]
 [ 1.  5.  0.  8.  7.]
 [ 9.  2.  8.  0.  4.]
 [ 5.  9.  4. 12.  0.]]


### b) All-pairs minimax path

In [13]:
def matrixminimax(matrix):
    dim = matrix.shape[0]
    assert(matrix.shape[0] == matrix.shape[1])
    
    multisteps = deepcopy(matrix)
    result = deepcopy(matrix)
    newrow = np.array([0.0, 0.0, 0.0, 0.0, 0.0])
    
    iterations = 0
    
    while 1:
        iterations += 1
        for i in range(dim):
            row = multisteps[i]
            for j in range(dim):
                col = matrix[:, j]
                result[i][j] = np.min(np.maximum(row, col))

        if (multisteps == result).all():
            print("minimax converged after", iterations - 1, "iterations")
            return result, iterations-1
        elif iterations > dim:
            raise "Negative Cycle detected"
            return None
        else:
            multisteps = deepcopy(result)

In [14]:
shortestpaths, iterations = matrixminimax(onestep)
print(shortestpaths)

minimax converged after 3 iterations
[[0. 6. 6. 8. 6.]
 [4. 0. 4. 8. 2.]
 [1. 5. 0. 8. 5.]
 [4. 2. 4. 0. 2.]
 [4. 5. 4. 8. 0.]]


### c)

Negative cycles can be detected by counting the number of iterations during which something changes in the matrix. If the iterations exceed the total number of nodes and still did not converge, then there must be negative cycles present. (see implementation above)

# 2. Distance Transform Watershed using Fiji

### b.) Distance Transform Watershed
Use the code block below to load the image you generated with Fiji and plot it overlayed with the original raw image.

In [ ]:
from cvf20.utils import plot_segm
raw = plt.imread("data/raw.png")
WS = plt.imread("data/distance-transform-WS.tif")

f, ax = plt.subplots(ncols=1, nrows=1, figsize=(15,15))
plot_segm(ax, WS, with_background_label=True, alpha_labels=0.4, background_image=raw)
plt.show()

### c.) Segmenting boundaries 
Use the code block below to load the image you generated with Fiji and plot it overlayed with the original raw image.

In [ ]:
from cvf20.utils import plot_segm
raw = plt.imread("data/raw.png")
WS = plt.imread("data/distance-transform-WS-no-boundaries.tif")

f, ax = plt.subplots(ncols=1, nrows=1, figsize=(15,15))
plot_segm(ax, WS, with_background_label=True, alpha_labels=0.4, background_image=raw)
plt.show()

# 3. Bonus: Connected Component Labeling

### b) Connected components on graphs
Use the code block below to test your implementation on a randomly generated graph with 100 vertices. For every pair of nodes, we introduce an edge with probability 0.02. This is usually known as Erdős-Rényi graph or binomial graph. 

You should find that the graph has one very big connected component and several small ones.

In [ ]:
from networkx.algorithms.components import number_connected_components
from networkx.generators.random_graphs import fast_gnp_random_graph

# We now generate a graph with 100 vertices. For every pair of nodes, we introduce an edge with probability 0.02
# This is usually known as Erdős-Rényi graph or binomial graph.
G = fast_gnp_random_graph(100, 0.02)
nodes = [n for n in G.nodes()]
edges = [e for e in G.edges()]

########################### 
# Your code starts here:
###########################

# Hint: keep in mind what you learned in the last assignment about the UnionFind data structure (Sheet 8, Exercise 1)    

size_connected_components = None

########################### 
# Your code ends here
###########################


if size_connected_components is not None:
    assert size_connected_components.shape[0] == number_connected_components(G)
    print("Size connected components: ", size_connected_components)
    print("Biggest connected component: {} vertices (out of 100)".format(size_connected_components.max()))